name: macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup vcpkg
      run: |
        chmod +x ./tools/install-vcpkg.sh
        ./tools/install-vcpkg.sh
      
    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh clean release skip_tests
        chmod +x ./build/examples/single-thing
        chmod +x ./build/examples/multiple-things
        chmod +x ./build/examples/gui-thing
        chmod +x ./build/test/tests

    - name: Run tests with -s flag
      run: |
          ./build/test/tests
    
    - name: Integration tests
      working-directory: ${{github.workspace}}/test/webthing-tester
      run: |
        chmod +x ./run-webthing-tester.sh
        ./run-webthing-tester.sh

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          ./build/examples/single-thing
          ./build/examples/multiple-things
          ./build/examples/gui-thing
          ./build/test/tests